# Generated by Django 6.0.7 on 2026-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photograph_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
