# Generated by Django 6.0.7 on 2026-07-28 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photograph_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='photograph_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
