# Generated by Django 6.0.7 on 2026-07-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photograph_photograph_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
